default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: logidze_tracking

test:
  <<: *default
  database: logidze_tracking_test

production:
  <<: *default
  database: logidze_tracking_pro
